### ISSUE TITLE
Barrel hammer unable to remove upgrades from sorting barrel.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Dynious/RefinedRelocation#320] opened 2015-06-09 01:26 UTC
Title nails it.

**Comment by blay09** [comment] 2015-06-09 14:35
This is a problem caused by what I described in #294 that comes with a non-native implementation on our side rather than a native one on JABBA's side.

The problem is that JABBA specifically checks for it's own barrel block in the barrel hammer item code. This could be fixed by JABBA instead checking for any block that extends BlockBarrel, but that only makes sense for >them< if they actually do the implementation on their side.

This might be possible to fix on our side with some weird workarounds and whatever, but I'd rather have it not work than making the mess even deeper and possibly causing more problems.

**Closed** 2017-03-14 17:38 UTC
Labels: compatibility, RIP 1.7.10 - won't fix / implement, wontfix
