### ISSUE TITLE
ME sorting interface breaks ME autocrafting

### ISSUE THREAD

**Issue by iarspider** [Dynious/RefinedRelocation#316] opened 2015-06-07 08:47 UTC
Forge: 10.13.3.1401-1710ls
Refined relocation: 1.0.8b
Applied Energetics: rv2-stable-5

I've got a huge wall of sorting barrels (left over from my old storage/sorting system) that I wanted to keep using after I switch to AE2. But, for some reason, plugging ME sorting interface into the AE system breaks autocrafting: http://imgur.com/a/o7jAH (the only change between the two screenshots is removing sorting interface from the AE system).

**Comment by NolanSyKinsley** [comment] 2015-06-07 17:11
Can confirm, ran into this same issue. It is not the sorting interface itself, as pluggin just taht in does not block it. I also saw reference to someone saying that sorting chests work fine and it is specifically the JABBA barrels causing the issue.

**Comment by NolanSyKinsley** [comment] 2015-06-07 21:07
I just checked and storage drawers are fine, it appears that it is indeed the barrels causing the issue.

**Comment by Shurhaian** [comment] 2015-07-16 14:17
This issue seems to be erratic. I've had it work for me a few times (Agrarian Skies 2 v1.1.7). Other times, not. Sometimes, reloading the world will make it start working again; sometimes it will not. I'm currently in a long stretch of "not" despite no changes to the barrel wall from the last time it was working.

It's starting to look like I'll need to just bite the bullet and not use the ME sorting interface at all, instead dedicating a storage bus to each and every barrel. This thing has been broken for quite a while now, and reported as fixed on at least one occasion that I saw back in January. I don't at all know how it works internally - if it works like a storage bus on an ME subnet, for instance (which I think would also cause #318 which references this; recursive networking AFAIK only goes one layer deep, putting the lie to the achievement name) - but whatever the case, it seems to be doing something that AE2 distinctly dislikes.

**Comment by iarspider** [comment] 2015-07-16 17:35
I've managed to work around this bug by putting ME sorting interface into it's own subnet.

**Comment by Shurhaian** [comment] 2015-07-16 18:16
Interesting. That's exactly the situation described in 318, which wasn't working for some. However, although I can see the items in the barrels (so 318 doesn't apply), autocrafting is still erratic. Which is better than "completely broken", but still vexing.

Trying to track down what causes it. Purely "processing" crafting seems fine - I can queue glass, which involves pulverizing cobble into gravel and gravel into sand, then smelting. I can craft wheat (from the barrels; I disconnected them temporarily to be sure I got all other wheat out of the system) into seeds. I cannot, however, make flour (HarvestCraft), which is purely an assembler crafting job but uses A) wheat from the barrels and B) "catalysts" (a mortar-and-pestle item, in this case) which are kept between operations. This is true even if there is wheat sitting in a low-priority storage on the main network, which should be used before the sorting interface (which is set to higher priority; AE2 extracts from low-priority first so as to eventually empty it in favor of higher-priority storage).

However, I can still craft other recipes with a catalyst (like Extra Utilities colored stone) even when the ME sorting interface is connected. But I cannot autocraft, say, Big Reactors reactor casings, which use no catalyst, mostly external processing, and just one assembler job to put the pieces together.

The moment I disconnect the sorting interface, all these recalcitrant recipes start working again.

I'm not sure what else I could test for at this point; I've tried to identify a pattern as to what works and what doesn't, and I'm stumped. The only thing I can say is a vague "simpler recipes seem more likely to work."

**Comment by iarspider** [comment] 2015-08-01 11:56
After a server reboot that setup broke again...

**Comment by Dynious** [comment] 2015-08-22 20:01
I updated the sorting barrel implementation, this might fix some of the issues here. I cannot confirm this though, as I cannot reproduce this issue consistently.

**Comment by LordTerbium** [comment] 2015-09-11 07:48
I don't know if this here is still up to date, but i wanted to report, what at least I think might be involved with this issue:
I tested this in a clean instance with forge 10.13.4.1492. The only mods installed are

appliedenergistics2-rv2-stable-10
ae2stuff-0.5.0.56-mc1.7.10
bdlib-1.9.2.104-mc1.7.10 (needed by ae2 stuff)
CodeChickenCore-1.7.10-1.0.6.43-universal
Jabba-1.2.1a_1.7.10
NotEnoughItems-1.7.10-1.0.4.107-universal
RefinedRelocation-1.7.10-1.0.8b

I had to wait quite a long time before the autocrafting refused to work. But instead of rejecting every crafting request(that's what it does on my server), it just doesn't accept the ones including items stored inside the sorting barrels.
And there only if the crafting task required to extract more than 64 items (a stack) from the barrel.

The two pictures explain the situation.

![2015-09-11_09 06 55](https://cloud.githubusercontent.com/assets/6330838/9809067/47685dda-5865-11e5-9635-08a696ab9d08.png)

The recipe for the sticky piston requires redstone and slimeballs, which are stored inside the sorting barrels. Here the recipe requires only 64 of each and I still can complete the autocrafting task.

![2015-09-11_09 11 52](https://cloud.githubusercontent.com/assets/6330838/9809069/4befe38c-5865-11e5-87fe-0e605a26a819.png)

Here I requested 65 pistons, which require 65 items of both, redstone and slime balls. Now it refuses to craft them. Maybe AE has difficulties at how to extract more than one stack from a barrel.
Neither reloading the world or restarting the client solved the problem.

Strangely enough on my server AE refuses to craft anything after a while.

Here two pictures to show my setup:
![2015-09-11_09 31 08](https://cloud.githubusercontent.com/assets/6330838/9809435/6be69eb2-5868-11e5-9762-98aa0c40482e.png)
![2015-09-11_09 31 18](https://cloud.githubusercontent.com/assets/6330838/9809436/6c1f0d2e-5868-11e5-9f0c-1be6d71852d3.png)

Hope i could help, because i really would like to my sorted barrels.

**Comment by cirion47** [comment] 2015-09-21 22:56
Im having the exact same problem using RefinedRelocation-1.7.10-1.0.8b. When i connect my Sorting barrels through the ME sorting interface to my AE network my ME crafting is broken (the start crafting button is grated out). When i disconnect them everything is fine again....

**Comment by blay09** [comment] 2015-10-06 01:52
The ME Sorting Interface is likely going to be removed in the future. It's causing quite a few issues and was never balanced in the first place (it basically replaces the need for several storage buses by one block).

**Closed** 2017-03-14 17:38 UTC
Labels: bug, compatibility, RIP 1.7.10 - won't fix / implement
